orchestrator: dea
dataset_format: dea-format
model_config: datasets/model_configs/gcp_data_engineering_agent_model.yaml
simulated_user_model_config: datasets/model_configs/gemini_2.5_pro_model.yaml
dataset_config: datasets/dea-tools/dea-live-conversational.evalset.json
env:
  SCENARIO_ID: "dea-live-conversational"
scorers:
  binary_rubric_scorer:
    model_config: datasets/model_configs/gemini_2.5_pro_model.yaml
  dataform_cloud_compile:
    gcp_project_id: !ENV ${EVAL_GCP_PROJECT_ID}
    gcp_region: !ENV ${EVAL_GCP_PROJECT_REGION}
    timeout_seconds: 300
  dataform_cloud_run:
    gcp_project_id: !ENV ${EVAL_GCP_PROJECT_ID}
    gcp_region: !ENV ${EVAL_GCP_PROJECT_REGION}
    timeout_seconds: 300
reporting:
  csv:
    output_directory: results
  bigquery:
    gcp_project_id: !ENV ${EVAL_GCP_PROJECT_ID}
runners:
  agent_runners: 1
set_up_script: datasets/dea-tools/scripts/setup_dataform.sh
tear_down_script: datasets/dea-tools/scripts/teardown_dataform.sh
dataform_workspace_gcs_archive:
  bucket: !ENV ${EVAL_GCP_PROJECT_ID}-evalbench-archives
  path_prefix: workspaces
  gcp_project_id: !ENV ${EVAL_GCP_PROJECT_ID}
