[supervisord]
nodaemon=true
logfile = /tmp/supervisord.log
logfile_maxbytes = 50MB
logfile_backups=5

[program:evalbench_frontend]
command=bash -c "gunicorn -w 12 -k gevent main:me --bind :$${PORT:-3000} --forwarded-allow-ips=\"*\" --timeout 120"
directory=/evalbench/viewer
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:precompute_trends]
command=python /evalbench/viewer/run_precompute.py
directory=/evalbench/viewer
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0